/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.greenlab.view;

import com.greenlab.controller.CustomerController;
import com.greenlab.controller.InvoiceController;
import com.greenlab.controller.PaymentController;
import com.greenlab.controller.ResivedPaymentController;
import com.greenlab.model.Customer;
import com.greenlab.model.Invoice;
import com.greenlab.model.ResivedPayment;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeon-IT
 */
public class CopyInvoice extends javax.swing.JPanel {
    
    PaymentController paymentController;
    DefaultTableModel dtm;
    InvoiceController invoiceController;
    CustomerController customerController;
    ResivedPaymentController resivedPaymentController;

    /**
     * Creates new form CopyInvoice
     */
    public CopyInvoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        customerCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InvoiceViewTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(960, 570));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Customer Name :");

        customerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Invoice List");

        InvoiceViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice  Id", "Date", "netTotal", "Total", "TotalDiscount", "Customer", "Customer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InvoiceViewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoiceViewTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(InvoiceViewTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboActionPerformed
        customerController = new CustomerController();
        invoiceController = new InvoiceController();
        resivedPaymentController = new ResivedPaymentController();
        paymentController = new PaymentController();

        String custName = customerCombo.getSelectedItem().toString();

        Customer customer =  customerController.getByName(custName);

        List<Invoice>invoices  = invoiceController.searchByCustomerId(customer.getId());

        if(invoices != null){
            dtm = (DefaultTableModel) InvoiceViewTable.getModel();
            dtm.setRowCount(0);
            for (Invoice invoice : invoices) {
                Object[]rowData = {invoice.getInvoice_id(),invoice.getDate(),invoice.getNetTotal(),invoice.getTotal(),invoice.getTotalDiscount(),invoice.getCustomer().getId(),invoice.getCustomer().getName()};
                dtm.addRow(rowData);
            }
        }

//        List<ResivedPayment> resivedPayments = resivedPaymentController.searchResivedPayment(customer.getId());
//        if(resivedPayments !=null){
//            dtm = (DefaultTableModel) resivedPTable.getModel();
//            dtm.setRowCount(0);
//            for(ResivedPayment resivedPayment : resivedPayments){
//
//                Object[]rowData = {resivedPayment.getId(),resivedPayment.getCheqNo(),resivedPayment.getDate(),resivedPayment.getCustomer().getId(),resivedPayment.getAmount(),resivedPayment.getInvoice().getInvoice_id(),resivedPayment.getBalance()};
//                dtm.addRow(rowData);
//            }

//        }

    }//GEN-LAST:event_customerComboActionPerformed

    private void InvoiceViewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceViewTableMouseClicked
//        dtm = (DefaultTableModel) InvoiceViewTable.getModel();
//        if(evt.getClickCount()==2){
//            int row =InvoiceViewTable.getSelectedRow();
//            String id = dtm.getValueAt(row, 0).toString();
//            String netTotal = dtm.getValueAt(row, 2).toString();
//            String cutid = dtm.getValueAt(row, 5).toString();
//
//            inoiceidTxt.setText(id);
//            amountTxt.setText(netTotal);
//            CustomerTxt.setText(cutid);
//
//            //////  Loard data payment table for invoice
//            Integer invoiceid = Integer.parseInt(id);
//            List<Payment>payments  = paymentController.searchPaymentwithInvId(invoiceid);
//
//            if(payments != null){
//                dtm = (DefaultTableModel) paymentTable.getModel();
//                dtm.setRowCount(0);
//
//                for (Payment payment : payments) {
//                    Object[]rowData = {payment.getId(),payment.getInvoice_id(),payment.getDate(),payment.getAmount(),payment.getPaidAmount(),payment.getBalance()};
//                    dtm.addRow(rowData);
//                }
//            }
//        }
    }//GEN-LAST:event_InvoiceViewTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InvoiceViewTable;
    private javax.swing.JComboBox<String> customerCombo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
