/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.greenlab.view;

import com.greenlab.controller.CustomerController;
import com.greenlab.model.Customer;
import com.greenlab.util.Validation;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author zeonit
 */
public class CustomerForm extends javax.swing.JPanel {

    CustomerController customerController;
    DefaultTableModel dtm;

    /**
     * Creates new form Customer
     */
    public CustomerForm() {
        initComponents();
        txtid.setEditable(false);
        loadCustomerTable();
        btnRemove.setVisible(false);
        loadCustomers();
        txtid.setVisible(false);
        AutoCompleteDecorator.decorate(customerCombo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        txtPhone2 = new javax.swing.JTextField();
        txtPhone3 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        customerCombo = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 27, 172, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Search       :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, 23));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Name          :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 138, 66, 23));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Address     :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 167, 66, 23));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Phone1      :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 196, 66, 23));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Phone2      :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 225, 66, 23));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Phone3      :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 254, 66, 23));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Email          :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 283, 66, 23));
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 130, 23));

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 141, 210, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 168, 210, -1));

        txtPhone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhone1KeyReleased(evt);
            }
        });
        add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 197, 210, -1));

        txtPhone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhone2KeyReleased(evt);
            }
        });
        add(txtPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 226, 210, -1));

        txtPhone3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhone3KeyReleased(evt);
            }
        });
        add(txtPhone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 255, 210, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 284, 210, -1));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Address", "Phone1", "Phone2", "Phone3", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 400, 680, 130));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 90, -1));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 80, -1));

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("customer list");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, -1));

        btnUpdate1.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 80, -1));

        customerCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerComboItemStateChanged(evt);
            }
        });
        customerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboActionPerformed(evt);
            }
        });
        add(customerCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean isAddedd = false;
        customerController = new CustomerController();
        String name = txtName.getText();
        String address = txtAddress.getText();
        String telphone1 = txtPhone1.getText();
        String telphone2 = txtPhone2.getText();
        String telphone3 = txtPhone3.getText();
        String email = txtEmail.getText();
        Customer customer = new Customer(name, address, telphone1, telphone2, telphone3, email);
        isAddedd = customerController.addCustomer(customer);
        if (isAddedd) {
            JOptionPane.showMessageDialog(this, "Added Success.");
            loadCustomerTable();
            txtid.setText("");
            txtName.setText("");
            txtAddress.setText("");
            txtPhone1.setText("");
            txtPhone2.setText("");
            txtPhone3.setText("");
            txtEmail.setText("");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        dtm = (DefaultTableModel) customerTable.getModel();
        if (evt.getClickCount() == 2) {
            int row = customerTable.getSelectedRow();
            String id = dtm.getValueAt(row, 0).toString();
            String name = dtm.getValueAt(row, 1).toString();
            String address = dtm.getValueAt(row, 2).toString();
            String telphone1 = dtm.getValueAt(row, 3).toString();
            String telphone2 = dtm.getValueAt(row, 4).toString();
            String telphone3 = dtm.getValueAt(row, 5).toString();
            String email = dtm.getValueAt(row, 6).toString();

            txtid.setText(id);
            txtName.setText(name);
            txtAddress.setText(address);
            txtPhone1.setText(telphone1);
            txtPhone2.setText(telphone2);
            txtPhone3.setText(telphone3);
            txtEmail.setText(email);

        }
    }//GEN-LAST:event_customerTableMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtid.setText("");
        txtName.setText("");
        txtAddress.setText("");
        txtPhone1.setText("");
        txtPhone2.setText("");
        txtPhone3.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        boolean isAddedd = false;
        customerController = new CustomerController();
        int id = Integer.parseInt(txtid.getText());
        String name = txtName.getText();
        String address = txtAddress.getText();
        String telphone1 = txtPhone1.getText();
        String telphone2 = txtPhone2.getText();
        String telphone3 = txtPhone3.getText();
        String email = txtEmail.getText();
        Customer customer = new Customer(id, name, address, telphone1, telphone2, telphone3, email);
        isAddedd = customerController.updateCustomer(customer);
        if (isAddedd) {
            JOptionPane.showMessageDialog(this, "Update Success.");
            loadCustomerTable();
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        boolean isDeleted = false;
        customerController = new CustomerController();
        dtm = (DefaultTableModel) customerTable.getModel();
        int dialogoption = JOptionPane.showConfirmDialog(this, "Do you want to delete this customer?");

        if (dialogoption == JOptionPane.YES_OPTION) {
            int row = customerTable.getSelectedRow();
            int id = Integer.parseInt(dtm.getValueAt(row, 0).toString());
            isDeleted = customerController.deleteCustomer(id);
            dtm.setRowCount(0);
            loadCustomerTable();
        }
        loadCustomerTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed

    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        Validation.name(txtName);
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        //Validation.name(txtName);
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtPhone1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhone1KeyReleased
        Validation.phoneNumber(txtPhone1, evt);
    }//GEN-LAST:event_txtPhone1KeyReleased

    private void txtPhone2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhone2KeyReleased
        Validation.phoneNumber(txtPhone2, evt);
    }//GEN-LAST:event_txtPhone2KeyReleased

    private void txtPhone3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhone3KeyReleased
        Validation.phoneNumber(txtPhone3, evt);
    }//GEN-LAST:event_txtPhone3KeyReleased

    private void customerComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerComboItemStateChanged
        if (customerCombo.getSelectedItem() != "None") {

            if (customerCombo.getSelectedItem() != null) {
                customerController = new CustomerController();
                String name = customerCombo.getSelectedItem().toString();
                Customer c = customerController.searchByName(name);
                txtName.setText(c.getName());
                txtAddress.setText(c.getAddress());
                txtPhone1.setText(c.getTelphone1());
                txtPhone2.setText(c.getTelphone2());
                txtPhone3.setText(c.getTelphone3());
                txtEmail.setText(c.getEmail());
            }
        } else {
            txtName.setText("");
            txtAddress.setText("");
            txtPhone1.setText("");
            txtPhone2.setText("");
            txtPhone3.setText("");
            txtEmail.setText("");
        }


    }//GEN-LAST:event_customerComboItemStateChanged

    private void customerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboActionPerformed

        //txtId.setText((String.valueOf(c.getId())));
    }//GEN-LAST:event_customerComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JComboBox<String> customerCombo;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPhone2;
    private javax.swing.JTextField txtPhone3;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

    private void loadCustomerTable() {
        customerController = new CustomerController();
        dtm = (DefaultTableModel) customerTable.getModel();
        dtm.getDataVector().removeAllElements();
        List<Customer> customers = customerController.getAllCustomer();
        for (Customer c : customers) {
            Object[] rowData = {c.getId(), c.getName(), c.getAddress(), c.getTelphone1(), c.getTelphone2(), c.getTelphone3(), c.getEmail()};
            dtm.addRow(rowData);
        }
    }

    public void loadCustomers() {
        customerController = new CustomerController();
        List<Customer> customer = customerController.getAllCustomer();
        //chkProduct.setSelected(false);
        if (customer != null) {
            customerCombo.removeAllItems();
            customerCombo.addItem("None");
            for (Customer customer1 : customer) {
                customerCombo.addItem(customer1.getName());
            }
        }
    }
}
