/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.greenlab.view;

import com.greenlab.images.Imagess;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author zeonit
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        headPabel.setBackground(new Color(51, 51, 51, 160));
        leftsidePanel.setBackground(new Color(102, 102, 102, 220));
        LoadPanel.setBackground(new Color(240, 240, 240, 102));
        ShowTime();
        ImageIcon imageIcon = new ImageIcon(Imagess.class.getResource("icon.png"));
        this.setIconImage(imageIcon.getImage());
//        try {
//            File f = new File(getClass().getResource("icon.png").getFile());
//            Image image = ImageIO.read(f);
//            setIconImage(image);
//        } catch (IOException ex) {
//            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println("err img");
//        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headPabel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TimeLable = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        leftsidePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pouintSaleButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSystemUtility = new javax.swing.JButton();
        LoadPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headPabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("reen Colour Lab Manage System");
        headPabel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, 763, 78));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Powered By");
        headPabel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1166, 11, 75, 38));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greenlab/images/3232.png"))); // NOI18N
        headPabel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1247, 11, 103, 38));

        TimeLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TimeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greenlab/images/se11.png"))); // NOI18N
        TimeLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TimeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimeLableMouseClicked(evt);
            }
        });
        headPabel.add(TimeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 50, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greenlab/images/14.png"))); // NOI18N
        headPabel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 90));

        jPanel1.add(headPabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));

        leftsidePanel.setBackground(new java.awt.Color(102, 102, 102));
        leftsidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Payment");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        leftsidePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 39));

        pouintSaleButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pouintSaleButton.setText("Point of Sale");
        pouintSaleButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pouintSaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pouintSaleButtonMouseClicked(evt);
            }
        });
        pouintSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pouintSaleButtonActionPerformed(evt);
            }
        });
        leftsidePanel.add(pouintSaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 230, 39));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Purchase Control");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        leftsidePanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, 39));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Customer Control");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        leftsidePanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 39));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Account Controls");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        leftsidePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 39));

        btnSystemUtility.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSystemUtility.setText("System Utility");
        btnSystemUtility.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSystemUtility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemUtilityActionPerformed(evt);
            }
        });
        leftsidePanel.add(btnSystemUtility, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 39));

        jPanel1.add(leftsidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 610));

        javax.swing.GroupLayout LoadPanelLayout = new javax.swing.GroupLayout(LoadPanel);
        LoadPanel.setLayout(LoadPanelLayout);
        LoadPanelLayout.setHorizontalGroup(
            LoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        LoadPanelLayout.setVerticalGroup(
            LoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel1.add(LoadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 1050, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greenlab/images/1234.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pouintSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pouintSaleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pouintSaleButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pouintSaleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pouintSaleButtonMouseClicked
        PointOfSale pos = new PointOfSale();
        LoadPanel.removeAll();
        pos.setSize(LoadPanel.getSize());
        LoadPanel.add(pos);
        LoadPanel.revalidate();
        LoadPanel.repaint();
    }//GEN-LAST:event_pouintSaleButtonMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        CustomerForm c = new CustomerForm();
        LoadPanel.removeAll();
        c.setSize(LoadPanel.getSize());
        LoadPanel.add(c);
        LoadPanel.revalidate();
        LoadPanel.repaint();
    }//GEN-LAST:event_jButton7MouseClicked

    private void btnSystemUtilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemUtilityActionPerformed
        UserPanel panel = new UserPanel();
        LoadPanel.removeAll();
        panel.setSize(LoadPanel.getSize());
        LoadPanel.add(panel);
        LoadPanel.revalidate();
        LoadPanel.repaint();
    }//GEN-LAST:event_btnSystemUtilityActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        PaymetForm pf = new PaymetForm();
        LoadPanel.removeAll();
        pf.setSize(LoadPanel.getSize());
        LoadPanel.add(pf);
        LoadPanel.revalidate();
        LoadPanel.repaint();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        ProductService ps = new ProductService();
        LoadPanel.removeAll();
        ps.setSize(LoadPanel.getSize());
        LoadPanel.add(ps);
        LoadPanel.revalidate();
        LoadPanel.repaint();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        AccountControllerForm af = new AccountControllerForm();
        LoadPanel.removeAll();
        af.setSize(LoadPanel.getSize());
        LoadPanel.add(af);
        LoadPanel.revalidate();
        LoadPanel.repaint();
    }//GEN-LAST:event_jButton2MouseClicked

    private void TimeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeLableMouseClicked
        new LoadPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TimeLableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoadPanel;
    private javax.swing.JLabel TimeLable;
    private javax.swing.JButton btnSystemUtility;
    private javax.swing.JPanel headPabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftsidePanel;
    private javax.swing.JButton pouintSaleButton;
    // End of variables declaration//GEN-END:variables

    private void ShowTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date D = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
//                timeLable.setText(s.format(D));

            }
        }).start();
    }
}
