/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.greenlab.view;

import com.greenlab.controller.ProductController;
import com.greenlab.controller.ServiceController;
import com.greenlab.model.Product;
import com.greenlab.model.Service;
import com.greenlab.util.Validation;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author zeonit
 */
public class ProductService extends javax.swing.JPanel {

    ProductController productController;
    ServiceController serviceController;
    DefaultTableModel dtm;

    /**
     * Creates new form ProductService
     */
    public ProductService() {
        initComponents();
        jRadioButton1.setSelected(true);
        txtId.setEditable(false);
        loadItemTable();
        jRadioButton2.setVisible(false);
        jRadioButton1.setVisible(false);
        loadItem();
        txtId.setVisible(false);
        AutoCompleteDecorator.decorate(itemCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPartNo = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtSellingPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        itemCombo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product an Service");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 20, 280, 25));

        jRadioButton1.setText("Product");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 70, -1));

        jRadioButton2.setText("Service");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Selling Price           :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Search                     : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Part No                     :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Descrption              :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 120, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cost                          :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 120, 20));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 140, -1));
        jPanel1.add(txtPartNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, -1));
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 210, -1));

        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        txtCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCostKeyReleased(evt);
            }
        });
        jPanel1.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 210, -1));

        txtSellingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSellingPriceKeyReleased(evt);
            }
        });
        jPanel1.add(txtSellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 210, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 70, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Part No", "Description", "Cost", "Selling Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 660, 150));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Item List");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Qty                           :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 120, 20));

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 210, -1));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        itemCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboActionPerformed(evt);
            }
        });
        jPanel1.add(itemCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            jRadioButton2.setSelected(false);
            txtPartNo.setEnabled(true);
            txtCost.setEnabled(true);
            txtQty.setEnabled(true);
            loadItemTable();
            txtCost.setText("");
            txtDescription.setText("");
            txtPartNo.setText("");
            txtSellingPrice.setText("");
            txtQty.setText("");
            txtId.setText("");

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            jRadioButton1.setSelected(false);
            txtPartNo.setEnabled(false);
            txtCost.setEnabled(false);
            txtQty.setEnabled(false);
            loadItemTable();
            txtCost.setText("");
            txtDescription.setText("");
            txtPartNo.setText("");
            txtSellingPrice.setText("");
            txtQty.setText("");
            txtId.setText("");
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        serviceController = new ServiceController();
        productController = new ProductController();
        boolean isAdded = false;

        if (jRadioButton1.isSelected()) {
            String partNo = txtPartNo.getText();
            String descripton = txtDescription.getText();
            Double qty = Double.parseDouble(txtQty.getText());
            Double cost = Double.parseDouble(txtCost.getText());
            Double selingPrice = Double.parseDouble(txtSellingPrice.getText());
            Product product = new Product(partNo, descripton, qty, cost, selingPrice);
            isAdded = productController.addProduct(product);
            loadItemTable();
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success.");
                txtCost.setText("");
                txtDescription.setText("");
                txtPartNo.setText("");
                txtSellingPrice.setText("");
                txtQty.setText("");
                txtId.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Added fail.");
            }
        }
        if (jRadioButton2.isSelected()) {
            String descripton = txtDescription.getText();
            Double selingPrice = Double.parseDouble(txtSellingPrice.getText());
            Service service = new Service(descripton, selingPrice);
            isAdded = serviceController.addService(service);
            loadItemTable();
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success.");
                txtCost.setText("");
                txtDescription.setText("");
                txtPartNo.setText("");
                txtSellingPrice.setText("");
                txtQty.setText("");
                txtId.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Added fail.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        serviceController = new ServiceController();
        productController = new ProductController();
        boolean isAdded = false;

        if (jRadioButton1.isSelected()) {
            int id = Integer.parseInt(txtId.getText());
            String partNo = txtPartNo.getText();
            String descripton = txtDescription.getText();
            Double qty = 12.0;
            Double cost = Double.parseDouble(txtCost.getText());
            Double selingPrice = Double.parseDouble(txtSellingPrice.getText());
            Product product = new Product(id, partNo, qty, descripton, cost, selingPrice);
            isAdded = productController.updateProduct(product);
            loadItemTable();
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Update Success.");
            } else {
                JOptionPane.showMessageDialog(this, "Update fail.");
            }
        }
        if (jRadioButton2.isSelected()) {
            int id = Integer.parseInt(txtId.getText());
            String descripton = txtDescription.getText();
            Double selingPrice = Double.parseDouble(txtSellingPrice.getText());
            Service service = new Service(id, descripton, selingPrice);
            isAdded = serviceController.updateService(service);
            loadItemTable();
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Update Success.");
            } else {
                JOptionPane.showMessageDialog(this, "Update fail.");
            }
        }
        loadItem();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtId.setText("");
        txtCost.setText("");
        txtDescription.setText("");
        txtPartNo.setText("");
        txtSellingPrice.setText("");
        txtQty.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        dtm = (DefaultTableModel) itemTable.getModel();
        if (evt.getClickCount() == 2) {
            int row = itemTable.getSelectedRow();
            String id = dtm.getValueAt(row, 0).toString();
            String partNo = dtm.getValueAt(row, 1).toString();
            String description = dtm.getValueAt(row, 2).toString();
            String cost = dtm.getValueAt(row, 3).toString();
            String sellingPrice = dtm.getValueAt(row, 4).toString();

            txtId.setText(id);
            txtPartNo.setText(partNo);
            txtDescription.setText(description);
            txtCost.setText(cost);
            txtSellingPrice.setText(sellingPrice);

        }
    }//GEN-LAST:event_itemTableMouseClicked

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        Validation.numberOnly(txtQty);
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtSellingPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellingPriceKeyReleased
        Validation.priceText(txtSellingPrice);
    }//GEN-LAST:event_txtSellingPriceKeyReleased

    private void txtCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostKeyReleased
        Validation.priceText(txtCost);
    }//GEN-LAST:event_txtCostKeyReleased

    private void itemComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboActionPerformed

        if (itemCombo.getSelectedItem() != "None") {
            String name = (String) itemCombo.getSelectedItem();
            productController = new ProductController();
            Product p = productController.searchByName(name);
            txtId.setText(String.valueOf(p.getProduct_id()));
            txtPartNo.setText(p.getPartNo());
            txtDescription.setText(p.getDescription());
            txtQty.setText(String.valueOf(p.getQty()));
            txtSellingPrice.setText(String.valueOf(p.getSellingPrice()));
            txtCost.setText(String.valueOf(p.getCost()));
        } else {
            txtId.setText("");
            txtPartNo.setText("");
            txtDescription.setText("");
            txtQty.setText("");
            txtSellingPrice.setText("");
            txtCost.setText("");
        }
    }//GEN-LAST:event_itemComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> itemCombo;
    private javax.swing.JTable itemTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPartNo;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables

    private void loadItemTable() {
        productController = new ProductController();
        serviceController = new ServiceController();
        dtm = (DefaultTableModel) itemTable.getModel();
        dtm.getDataVector().removeAllElements();
        List<Product> products = productController.getAllProduct();
        List<Service> services = serviceController.getAllServices();
        if (jRadioButton1.isSelected()) {
            for (Product p : products) {
                Object[] rowData = {p.getProduct_id(), p.getPartNo(), p.getDescription(), p.getCost(), p.getSellingPrice()};
                dtm.addRow(rowData);
            }
        }
        if (jRadioButton2.isSelected()) {
            for (Service s : services) {
                Object[] rowData = {s.getId(), "none", s.getService(), 0, s.getPrice()};
                dtm.addRow(rowData);
            }

        }
    }

    private void loadItem() {
        productController = new ProductController();
        List<Product> products = productController.getAllProduct();
        //chkService.setSelected(false);
        if (products != null) {
            itemCombo.removeAllItems();
            itemCombo.addItem("None");
            for (Product product : products) {
                itemCombo.addItem(product.getDescription());
            }
        }
    }
}
